2023-12-25 04:28:10,597 INFO    StreamThr :19632 [internal.py:wandb_internal():86] W&B internal server running at pid: 19632, started at: 2023-12-25 04:28:10.596087
2023-12-25 04:28:10,598 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status
2023-12-25 04:28:10,604 INFO    WriterThread:19632 [datastore.py:open_for_write():85] open: Q:\AD project\wandb\run-20231225_042810-wj8faala\run-wj8faala.wandb
2023-12-25 04:28:10,605 DEBUG   SenderThread:19632 [sender.py:send():382] send: header
2023-12-25 04:28:10,605 DEBUG   SenderThread:19632 [sender.py:send():382] send: run
2023-12-25 04:28:10,867 INFO    SenderThread:19632 [dir_watcher.py:__init__():211] watching files in: Q:\AD project\wandb\run-20231225_042810-wj8faala\files
2023-12-25 04:28:10,867 INFO    SenderThread:19632 [sender.py:_start_run_threads():1136] run started: wj8faala with start time 1703496490.597088
2023-12-25 04:28:10,869 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: check_version
2023-12-25 04:28:10,870 DEBUG   SenderThread:19632 [sender.py:send_request():409] send_request: check_version
2023-12-25 04:28:11,025 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: run_start
2023-12-25 04:28:12,317 DEBUG   HandlerThread:19632 [system_info.py:__init__():32] System info init
2023-12-25 04:28:12,317 DEBUG   HandlerThread:19632 [system_info.py:__init__():47] System info init done
2023-12-25 04:28:12,317 INFO    HandlerThread:19632 [system_monitor.py:start():194] Starting system monitor
2023-12-25 04:28:12,317 INFO    SystemMonitor:19632 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-12-25 04:28:12,317 INFO    HandlerThread:19632 [system_monitor.py:probe():214] Collecting system info
2023-12-25 04:28:12,323 INFO    SystemMonitor:19632 [interfaces.py:start():190] Started cpu monitoring
2023-12-25 04:28:12,323 INFO    SystemMonitor:19632 [interfaces.py:start():190] Started disk monitoring
2023-12-25 04:28:12,324 INFO    SystemMonitor:19632 [interfaces.py:start():190] Started gpu monitoring
2023-12-25 04:28:12,324 INFO    SystemMonitor:19632 [interfaces.py:start():190] Started memory monitoring
2023-12-25 04:28:12,333 INFO    SystemMonitor:19632 [interfaces.py:start():190] Started network monitoring
2023-12-25 04:28:12,349 DEBUG   HandlerThread:19632 [system_info.py:probe():196] Probing system
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [gitlib.py:_init_repo():56] git repository is invalid
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [system_info.py:probe():244] Probing system done
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.9.18', 'heartbeatAt': '2023-12-25T09:28:12.349231', 'startedAt': '2023-12-25T09:28:10.586466', 'docker': None, 'cuda': None, 'args': ('--yt_links_filename', 'data/temp.txt', '--output_path', 'TEMP'), 'state': 'running', 'program': 'Q:\\AD project\\transcripts_main.py', 'codePathLocal': 'transcripts_main.py', 'codePath': 'transcripts_main.py', 'host': 'LAPTOP-QF1FUNPH', 'username': 'astar', 'executable': 'C:\\Users\\astar\\anaconda3\\envs\\tf-gpu\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 1901.0, 'min': 0.0, 'max': 1901.0}, 'cpu_freq_per_core': [{'current': 1901.0, 'min': 0.0, 'max': 1901.0}], 'disk': {'/': {'total': 48.827144622802734, 'used': 43.54924392700195}}, 'gpu': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 15.355525970458984}}
2023-12-25 04:28:12,350 INFO    HandlerThread:19632 [system_monitor.py:probe():224] Finished collecting system info
2023-12-25 04:28:12,350 INFO    HandlerThread:19632 [system_monitor.py:probe():227] Publishing system info
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-25 04:28:12,350 DEBUG   HandlerThread:19632 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-12-25 04:28:12,355 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:12,364 ERROR   HandlerThread:19632 [system_info.py:_save_conda():86] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\astar\anaconda3\envs\tf-gpu\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    subprocess.call(
  File "C:\Users\astar\anaconda3\envs\tf-gpu\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\astar\anaconda3\envs\tf-gpu\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\astar\anaconda3\envs\tf-gpu\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-12-25 04:28:12,366 DEBUG   HandlerThread:19632 [system_info.py:_save_conda():87] Saving conda packages done
2023-12-25 04:28:12,366 INFO    HandlerThread:19632 [system_monitor.py:probe():229] Finished publishing system info
2023-12-25 04:28:12,375 DEBUG   SenderThread:19632 [sender.py:send():382] send: files
2023-12-25 04:28:12,375 INFO    SenderThread:19632 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2023-12-25 04:28:12,382 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: stop_status
2023-12-25 04:28:12,382 DEBUG   SenderThread:19632 [sender.py:send_request():409] send_request: stop_status
2023-12-25 04:28:12,384 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: internal_messages
2023-12-25 04:28:12,576 DEBUG   SenderThread:19632 [sender.py:send():382] send: telemetry
2023-12-25 04:28:12,876 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_created():271] file/dir created: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\conda-environment.yaml
2023-12-25 04:28:12,877 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_created():271] file/dir created: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\requirements.txt
2023-12-25 04:28:12,877 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_created():271] file/dir created: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\wandb-metadata.json
2023-12-25 04:28:12,965 INFO    wandb-upload_0:19632 [upload_job.py:push():131] Uploaded file C:\Users\astar\AppData\Local\Temp\tmpnjb2bh_qwandb\l23aggdu-wandb-metadata.json
2023-12-25 04:28:14,863 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:14,863 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:15,606 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:17,369 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:17,369 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:19,897 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:19,897 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:20,650 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:22,397 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:22,397 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-25 04:28:22,921 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_created():271] file/dir created: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\output.log
2023-12-25 04:28:24,419 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:24,933 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_modified():288] file/dir modified: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\output.log
2023-12-25 04:28:26,252 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:26,431 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:26,953 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_modified():288] file/dir modified: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\output.log
2023-12-25 04:28:27,386 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: internal_messages
2023-12-25 04:28:27,401 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: stop_status
2023-12-25 04:28:27,401 DEBUG   SenderThread:19632 [sender.py:send_request():409] send_request: stop_status
2023-12-25 04:28:27,962 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_modified():288] file/dir modified: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\output.log
2023-12-25 04:28:28,440 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:30,450 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:31,597 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:32,463 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:34,473 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:36,488 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:36,638 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:38,500 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:40,522 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:41,700 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:42,093 INFO    Thread-16 :19632 [dir_watcher.py:_on_file_modified():288] file/dir modified: Q:\AD project\wandb\run-20231225_042810-wj8faala\files\config.yaml
2023-12-25 04:28:42,392 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: internal_messages
2023-12-25 04:28:42,408 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: stop_status
2023-12-25 04:28:42,409 DEBUG   SenderThread:19632 [sender.py:send_request():409] send_request: stop_status
2023-12-25 04:28:42,541 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:44,621 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:46,640 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:47,645 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:48,647 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:50,662 ERROR   gpu       :19632 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-25 04:28:52,530 INFO    memory    :19632 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2023-12-25 04:28:52,530 DEBUG   SystemMonitor:19632 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-12-25 04:28:52,530 DEBUG   SystemMonitor:19632 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2023-12-25 04:28:52,531 DEBUG   SystemMonitor:19632 [system_monitor.py:_start():183] Publishing last batch of metrics
2023-12-25 04:28:52,533 DEBUG   SenderThread:19632 [sender.py:send():382] send: stats
2023-12-25 04:28:53,536 DEBUG   HandlerThread:19632 [handler.py:handle_request():146] handle_request: status_report
2023-12-25 04:28:55,415 INFO    MainThread:19632 [internal.py:handle_exit():76] Internal process exited
